version: "3.5"

volumes:
    harpia-postgres-data:
        driver: local

services:
    webserver:
        image: nginx:alpine
        container_name: challenge-promobit-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8082:80"

    php-fpm:
        build: docker/php-fpm
        container_name: challenge-promobit-php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/cli/conf.d/99-overrides.ini
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/mods-available/99-overrides.ini

