version: "3.5"
services:

    webserver:
        image: nginx:alpine
        container_name: bprv-p4-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"

    php-fpm:
        build: docker/php-fpm
        container_name: bprv-p4-php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/cli/conf.d/99-overrides.ini
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/mods-available/99-overrides.ini

    #memcached:
    #    image: memcached:alpine
    #    container_name: bprv-p4-memcached
    #
    #redis:
    #    image: redis:alpine
    #    container_name: bprv-p4-redis
    #
    #postgres:
    #    image: postgres:11.1-alpine
    #    container_name: bprv-p4-postgres
    #    working_dir: /application
    #    volumes:
    #        - .:/application
    #    environment:
    #        - POSTGRES_USER=root
    #        - POSTGRES_PASSWORD=root
    #        - POSTGRES_DB=root
    #    ports:
    #        - "8004:5432"


#version: '3.5'
#services:
#    app:
#        image: markteam/docker-php:7.3
#        container_name: bprv-p4
#        working_dir: /var/www/app
#        restart: always
#        volumes:
#            - .:/application
#        ports:
#            - "82:80"
